const PDFDocument = require("pdfkit");
const Course = require("../models/Course");

exports.generateCoursePDF = async (req, res) => {
  try {
    const course = await Course.findById(req.params.courseId).populate(
      "teacher",
      "name"
    );

    if (!course) {
      return res.status(404).json({ message: "Course not found" });
    }

    // 👨‍🏫 Teacher → only own course
    if (req.user.role === "teacher") {
      if (course.teacher._id.toString() !== req.user._id.toString()) {
        return res.status(403).json({ message: "Access denied" });
      }
    }

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${course.title}_details.pdf`
    );

    doc.pipe(res);

    // =========================
    // HEADER
    // =========================
    doc
      .fontSize(22)
      .text("Course Details", { align: "center", underline: true });

    doc.moveDown(2);

    // =========================
    // COURSE INFO
    // =========================
    doc.fontSize(16).text("Course Information", { underline: true });
    doc.moveDown();

    doc.fontSize(12);

    if (course.title)
      doc.text(`Title: ${course.title}`);

    if (course.courseCode)
      doc.text(`Course Code: ${course.courseCode}`);

    if (course.creditHours)
      doc.text(`Credit Hours: ${course.creditHours}`);

    if (course.joinCode)
      doc.text(`Join Code: ${course.joinCode}`);

    doc.moveDown();

    // =========================
    // SYLLABUS
    // =========================
    if (course.syllabus) {
      doc.fontSize(16).text("Syllabus", { underline: true });
      doc.moveDown();

      doc.fontSize(12).text(course.syllabus, {
        align: "justify",
      });

      doc.moveDown();
    }

    // =========================
    // BOOKS
    // =========================
    if (course.books && course.books.length > 0) {
      doc.fontSize(16).text("Recommended Books", { underline: true });
      doc.moveDown();

      doc.fontSize(12);

      course.books.forEach((book, index) => {
        doc.text(`${index + 1}. ${book}`);
      });

      doc.moveDown();
    }

    // =========================
    // INSTRUCTOR
    // =========================
    if (course.teacher) {
      doc.fontSize(16).text("Instructor", { underline: true });
      doc.moveDown();

      doc.fontSize(12);

      if (course.teacher.name)
        doc.text(`Name: ${course.teacher.name}`);

      doc.moveDown();
    }

    // =========================
    // METADATA
    // =========================
    doc.fontSize(16).text("Additional Details", { underline: true });
    doc.moveDown();

    doc.fontSize(12);

    if (course.createdAt)
      doc.text(
        `Created At: ${new Date(course.createdAt).toLocaleDateString()}`
      );

    if (course.updatedAt)
      doc.text(
        `Last Updated: ${new Date(course.updatedAt).toLocaleDateString()}`
      );

    doc.moveDown(2);

    // =========================
    // FOOTER
    // =========================
    doc
      .fontSize(10)
      .fillColor("gray")
      .text("Generated by Smart Teacher System", {
        align: "center",
      });

    doc.end();
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};