// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOP2kfCCaIXGvgPtGYvcNH6k4tZHMzPK0',
    appId: '1:98935133919:web:7fb5595ebdf7cc04c5fb6a',
    messagingSenderId: '98935133919',
    projectId: 'smart-teacher-assistant100',
    authDomain: 'smart-teacher-assistant100.firebaseapp.com',
    storageBucket: 'smart-teacher-assistant100.firebasestorage.app',
    measurementId: 'G-7T7PVS5PRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBJTlnEBe-hqrdRLpeWu978U-lvVX57Y',
    appId: '1:98935133919:android:119a540281717a4ac5fb6a',
    messagingSenderId: '98935133919',
    projectId: 'smart-teacher-assistant100',
    storageBucket: 'smart-teacher-assistant100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwOzMm2iDVleRMvo9wjYbdEOKgQrbSEsA',
    appId: '1:98935133919:ios:37cd9b57823c27bfc5fb6a',
    messagingSenderId: '98935133919',
    projectId: 'smart-teacher-assistant100',
    storageBucket: 'smart-teacher-assistant100.firebasestorage.app',
    androidClientId: '98935133919-p4mmu2qhpe6dc84stagq294a7pumes71.apps.googleusercontent.com',
    iosClientId: '98935133919-3olrqjifo01fm4uga39jm1aeu8d1j06u.apps.googleusercontent.com',
    iosBundleId: 'com.hasnain.smartteacherassistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwOzMm2iDVleRMvo9wjYbdEOKgQrbSEsA',
    appId: '1:98935133919:ios:12b0150bb61489a8c5fb6a',
    messagingSenderId: '98935133919',
    projectId: 'smart-teacher-assistant100',
    storageBucket: 'smart-teacher-assistant100.firebasestorage.app',
    androidClientId: '98935133919-p4mmu2qhpe6dc84stagq294a7pumes71.apps.googleusercontent.com',
    iosClientId: '98935133919-s1r7s15s6u5glj58rl5rpve30vmb2t32.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontened',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOP2kfCCaIXGvgPtGYvcNH6k4tZHMzPK0',
    appId: '1:98935133919:web:5f2d763077630011c5fb6a',
    messagingSenderId: '98935133919',
    projectId: 'smart-teacher-assistant100',
    authDomain: 'smart-teacher-assistant100.firebaseapp.com',
    storageBucket: 'smart-teacher-assistant100.firebasestorage.app',
    measurementId: 'G-RN32EN0NRZ',
  );
}
