const PDFDocument = require("pdfkit");
const fs = require("fs");

exports.generatePlanPDF = (data, filePath) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        size: "A4",
      });

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // ================= HEADER =================
      doc
        .fontSize(22)
        .font("Helvetica-Bold")
        .text(data.title || "AI Generated 18 Week Plan", {
          align: "center",
        });

      doc.moveDown(0.5);

      doc
        .fontSize(12)
        .font("Helvetica")
        .fillColor("#555")
        .text(data.description || "Course Weekly Plan", {
          align: "center",
        });

      doc.moveDown(1.5);

      // Divider
      doc
        .moveTo(50, doc.y)
        .lineTo(550, doc.y)
        .strokeColor("#cccccc")
        .stroke();

      doc.moveDown(1.5);

      // ================= WEEKS =================
      (data.weeks || []).forEach((week) => {
        if (doc.y > 700) doc.addPage();

        // WEEK TITLE
        doc
          .fontSize(16)
          .font("Helvetica-Bold")
          .fillColor("#000")
          .text(`Week ${week.weekNumber}: ${week.title || ""}`);

        doc.moveDown(0.5);

        // ================= TOPICS =================
        if (week.topics && week.topics.length > 0) {
          doc.fontSize(12).font("Helvetica-Bold").text("Topics:");

          week.topics.forEach((t) => {
            doc.font("Helvetica").text(`• ${t}`, { indent: 15 });
          });

          doc.moveDown(0.5);
        }

        // ================= OBJECTIVES =================
        if (week.objectives && week.objectives.length > 0) {
          doc.font("Helvetica-Bold").text("Objectives:");

          week.objectives.forEach((o) => {
            doc.font("Helvetica").text(`• ${o}`, { indent: 15 });
          });

          doc.moveDown(0.5);
        }

        // ================= TASKS =================
        if (week.tasks && week.tasks.length > 0) {
          doc.font("Helvetica-Bold").text("Tasks:");

          week.tasks.forEach((t) => {
            doc.font("Helvetica").text(`• ${t}`, { indent: 15 });
          });

          doc.moveDown(0.5);
        }

        // Divider
        doc
          .moveTo(50, doc.y)
          .lineTo(550, doc.y)
          .strokeColor("#eeeeee")
          .stroke();

        doc.moveDown(1);
      });

      // ================= FOOTER =================
      doc.moveDown(2);

      doc
        .fontSize(10)
        .fillColor("#888")
        .text(
          `Generated by AI System • ${new Date().toLocaleDateString()}`,
          { align: "center" }
        );

      doc.end();

      stream.on("finish", () => resolve(filePath));
      stream.on("error", reject);
    } catch (error) {
      reject(error);
    }
  });
};